lib/haz_cash_web/router.ex
defmodule HazCashWeb.Router do
  use HazCashWeb, :router

  import HazCashWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {HazCashWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
    plug HazCash.Admins.Pipeline
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :graphql do
    plug HazCashWeb.Context
  end

  # Set the layout for when an admin signs in
  pipeline :admin_session_layout do
    plug :put_root_layout, {HazCashWeb.Admin.LayoutView, :session}
  end

  pipeline :require_current_admin do
    plug HazCashWeb.Plugs.RequireCurrentAdmin
  end

  # Set the main layout for the admin area
  pipeline :admin_layout do
    plug :put_root_layout, {HazCashWeb.Admin.LayoutView, :root}
  end

  # Set the layout for when a user registers or signs in
  pipeline :session_layout do
    plug :put_root_layout, {HazCashWeb.LayoutView, :session}
  end

  scope "/", HazCashWeb do
    pipe_through :browser

    live "/", PageLive, :index
    live "/pricing", PricingLive.Index, :index
    get "/return_from_stripe", StripeReturnController, :new
  end

  scope "/webhooks", HazCashWeb do
    pipe_through :api

    post "/stripe", StripeWebhookController, :create
  end

  # Other scopes may use custom stacks.
  # scope "/api", HazCashWeb do
  #   pipe_through :api
  # end

  scope path: "/feature-flags" do
    pipe_through [:browser, :require_current_admin]
    forward "/", FunWithFlags.UI.Router, namespace: "feature-flags"
  end


  scope "/api" do
    pipe_through :graphql

    forward "/", Absinthe.Plug, schema: HazCashWeb.Schema
  end

  if Application.get_env(:haz_cash, :env) == :dev do
    forward "/graphiql", Absinthe.Plug.GraphiQL, schema: HazCashWeb.Schema
  end
  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Application.get_env(:haz_cash, :env) in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: HazCashWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Application.get_env(:haz_cash, :env) == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", HazCashWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated, :session_layout]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", HazCashWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
    post "/create-customer-portal-session", StripeCustomerPortalSession, :create

    live_session :current_user, on_mount: HazCashWeb.Live.UserAuth do
      live "/accounts", AccountLive.Index, :index
      live "/accounts/:account_id/members", MemberLive.Index, :index
      live "/subscriptions/new", SubscriptionLive.New, :new
      live "/billing", BillingLive.Index, :index
    end
  end

  # This block hold the routes that requires an authenticated user with an active subscription.
  scope "/", HazCashWeb do
    pipe_through [:browser, :require_authenticated_user] #:require_active_subscription]
    # Add non-live view routes here

    live_session :current_user_with_subscription, on_mount: HazCashWeb.Live.UserAuth do
    
    live "/home", HomeLive, :index

    live "/home/expenses/new", HomeLive, :new_expenses
    live "/home/expenses/:ids", HomeLive, :expenses


    live "/transfers", TransferLive.Index, :index
    live "/transfers/new", TransferLive.Index, :new
    live "/transfers/:id/edit", TransferLive.Index, :edit

    live "/transfers/:id", TransferLive.Show, :show
    live "/transfers/:id/show/edit", TransferLive.Show, :edit
        
    live "/expense_accounts", ExpenseAccountLive.Index, :index
    live "/expense_accounts/new", ExpenseAccountLive.Index, :new
    live "/expense_accounts/:id/edit", ExpenseAccountLive.Index, :edit

    live "/expense_accounts/:id", ExpenseAccountLive.Show, :show
    live "/expense_accounts/:id/show/edit", ExpenseAccountLive.Show, :edit
    
    

    live "/expenses", ExpenseLive.Index, :index
    live "/expenses/new", ExpenseLive.Index, :new
    live "/expenses/:id/edit", ExpenseLive.Index, :edit

    live "/expenses/:id", ExpenseLive.Show, :show
    live "/expenses/:id/show/edit", ExpenseLive.Show, :edit
    
    
    

      # Add live view routes here
      live "/accounts", AccountLive.Index, :index
    end
  end

  scope "/", HazCashWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end

  scope "/admin", HazCashWeb.Admin, as: :admin do
    pipe_through [:browser, :admin_session_layout]

    get "/sign_in", SessionController, :new
    post "/sign_in", SessionController, :create
    delete "/sign_out", SessionController, :delete
    get "/sign_out", SessionController, :delete
    get "/reset_password", ResetPasswordController, :new
    post "/reset_password", ResetPasswordController, :create
    get "/reset_password/:token", ResetPasswordController, :show
  end

  scope "/admin", HazCashWeb.Admin, as: :admin do
    pipe_through [:browser, :require_current_admin, :admin_layout]

    live "/", DashboardLive.Index, :index
    live "/settings", SettingLive.Edit, :edit

    post "/impersonate/:id", UserImpersonationController, :create

    live "/accounts", AccountLive.Index, :index
    live "/accounts/new", AccountLive.Index, :new
    live "/accounts/:id/edit", AccountLive.Index, :edit

    live "/accounts/:id", AccountLive.Show, :show
    live "/accounts/:id/show/edit", AccountLive.Show, :edit

    live "/users", UserLive.Index, :index
    live "/users/new", UserLive.Index, :new
    live "/users/:id", UserLive.Show, :show

    ## BILLING
    live "/customers", CustomerLive.Index, :index
    live "/customers/:id", CustomerLive.Show, :show

    live "/products", ProductLive.Index, :index
    live "/products/:id/edit", ProductLive.Index, :edit
    live "/products/:id", ProductLive.Show, :show
    live "/products/:id/show/edit", ProductLive.Show, :edit

    live "/products/:product_id/plans", PlanLive.Index, :index
    live "/products/:product_id/plans/:id", PlanLive.Show, :show

    live "/subscriptions", SubscriptionLive.Index, :index
    live "/subscriptions/:id", SubscriptionLive.Show, :show

    live "/invoices", InvoiceLive.Index, :index
  end
end

lib/haz_cash_web/live/admin/customer_live/index.ex
defmodule HazCashWeb.Admin.CustomerLive.Index do
  @moduledoc """
  The admin customers index page.
  """
  use HazCashWeb, :live_view
  import SaasKit.LiveComponents.DataTable

  alias HazCash.Billing.Customers

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(params, _url, socket) do
    {
      :noreply,
      socket
      |> assign(:params, params)
      |> assign(:page_title, "Listing Customers")
      |> assign(get_customers_assigns(params))
      |> pagination_assigns()
    }
  end

  @impl true
  def handle_event("delete", %{"id" => id}, socket) do
    customer = Customers.get_customer!(id)
    {:ok, _} = Customers.delete_customer(customer)

    {:noreply, assign(socket, get_customers_assigns(socket.assigns.params))}
  end

  defp get_customers_assigns(params) do
    case Customers.paginate_customers(params) do
      {:ok, assigns} -> assigns
      _ -> %{}
    end
  end
end

lib/haz_cash_web/live/admin/customer_live/show.ex
defmodule HazCashWeb.Admin.CustomerLive.Show do
  @moduledoc """
  The admin customer show page.
  """
  use HazCashWeb, :live_view

  alias HazCash.Billing.Customers

  @impl true
  def mount(_params, _session, socket) do
    {:ok, socket}
  end

  @impl true
  def handle_params(%{"id" => id}, _, socket) do
    customer =
      Customers.get_customer!(id)
      |> Customers.with_subscriptions()

    {:noreply,
     socket
     |> assign(:page_title, page_title(socket.assigns.live_action))
     |> assign(:customer, customer)}
  end

  defp page_title(:show), do: "Show Customer"
end

lib/haz_cash_web/live/admin/customer_live/index.html.heex
<.admin_page_heading title="Customers">
  <:link><%= live_redirect "Dashboard", to: Routes.admin_dashboard_index_path(@socket, :index) %></:link>
  <:link><%= live_redirect "Customers", to: Routes.admin_customer_index_path(@socket, :index) %></:link>

  <div class="btn-group">
    <%= live_patch to: Routes.admin_subscription_index_path(@socket, :index), class: "btn btn-outline" do %>
      Subscriptions
    <% end %>
    <%= live_patch to: Routes.admin_product_index_path(@socket, :index), class: "btn btn-outline" do %>
      Products
    <% end %>
    <%= live_patch to: Routes.admin_customer_index_path(@socket, :index), class: "btn btn-outline" do %>
      Customers
    <% end %>
    <%= live_patch to: Routes.admin_invoice_index_path(@socket, :index), class: "btn btn-outline" do %>
      Invoices
    <% end %>
  </div>
</.admin_page_heading>

<.admin_card>
  <div class="overflow-x-auto">
    <table class="table w-full">
      <thead>
        <tr>
          <th>
            <.data_table_link sort={:email} params={@params}>
              Email
            </.data_table_link>
          </th>
          <th>
            <.data_table_link sort={:stripe_id} params={@params}>
              Stripe
            </.data_table_link>
          </th>
          <th>
            <.data_table_link sort={:card_brand} params={@params}>
              Card brand
            </.data_table_link>
          </th>
          <th>
            <.data_table_link sort={:card_exp_month} params={@params}>
              Card exp month
            </.data_table_link>
          </th>
          <th>
            <.data_table_link sort={:card_exp_year} params={@params}>
              Card exp year
            </.data_table_link>
          </th>
          <th>
            <.data_table_link sort={:card_last4} params={@params}>
              Card last4
            </.data_table_link>
          </th>
          <th>
            <.data_table_link sort={:inserted_at} params={@params}>
              Created
            </.data_table_link>
          </th>

          <th></th>
        </tr>
      </thead>
      <tbody id="customers">
<%= for customer <- @entries do %>
        <tr id={"customer-#{customer.id}"} class="text-sm">
          <td><%= customer.email %></td>
          <td><%= customer.stripe_id %></td>
          <td><%= customer.card_brand %></td>
          <td><%= customer.card_exp_month %></td>
          <td><%= customer.card_exp_year %></td>
          <td><%= customer.card_last4 %></td>
          <td><%= Calendar.strftime customer.inserted_at, "%x" %></td>
          <td class="text-right">
            <span><%= live_redirect "Show", to: Routes.admin_customer_show_path(@socket, :show, customer), class: "link link-primary" %></span>
          </td>
        </tr>
<% end %>
      </tbody>
    </table>
  </div>

  <div class="mt-2 mb-4">
    <.pagination params={@params} {@pagination_assigns} />
  </div>
</.admin_card>

lib/haz_cash_web/live/admin/customer_live/show.html.heex
<.admin_page_heading title="Customers">
  <:link><%= live_redirect "Dashboard", to: Routes.admin_dashboard_index_path(@socket, :index) %></:link>
  <:link><%= live_redirect "Customers", to: Routes.admin_customer_index_path(@socket, :index) %></:link>
  <:link><%= live_redirect "Page", to: Routes.admin_customer_show_path(@socket, :show, @customer) %></:link>
</.admin_page_heading>

<div class="flex flex-wrap">
  <div class="w-full lg:w-2/3 grid grid-cols-1 gap-8">
    <.admin_card>
      <div class="flex items-center justify-between px-4 py-3 border-b border-base-200">
        <div class="prose">
          <h3>Show Customer</h3>
        </div>
      </div>
      <div class="card-body prose">
        <div>
          <strong>Email:</strong>
          <%= @customer.email %>
        </div>
        <div>
          <strong>Stripe:</strong>
          <%= @customer.stripe_id %>
        </div>
        <div>
          <strong>Card brand:</strong>
          <%= @customer.card_brand %>
        </div>
        <div>
          <strong>Card exp month:</strong>
          <%= @customer.card_exp_month %>
        </div>
        <div>
          <strong>Card exp year:</strong>
          <%= @customer.card_exp_year %>
        </div>
        <div>
          <strong>Card last4:</strong>
          <%= @customer.card_last4 %>
        </div>
      </div>
      <div class="border-t card-actions border-base-200">
        <%= live_redirect "Back", to: Routes.admin_customer_index_path(@socket, :index), class: "btn btn-link" %>
      </div>
    </.admin_card>

    <div class="prose">
      <h2>Subscriptions</h2>
    </div>

    <.admin_card>
      <div class="overflow-x-auto">
        <table class="table w-full">
          <thead>
            <tr>
              <th>Created</th>
              <th>Current period start</th>
              <th>Current period end at</th>
              <th>Cancel at</th>
              <th>Canceled at</th>
              <th>Status</th>
              <th>Stripe</th>

              <th></th>
            </tr>
          </thead>
          <tbody id="subscriptions">
  <%= for subscription <- @customer.subscriptions do %>
            <tr id={"subscription-#{subscription.id}"} class="text-sm">
              <th><%= human_date subscription.inserted_at %></th>
              <td><%= human_date subscription.current_period_start %></td>
              <td><%= human_date subscription.current_period_end_at %></td>
              <td><%= human_date subscription.cancel_at %></td>
              <td><%= human_date subscription.canceled_at %></td>
              <td><%= subscription.status %></td>
              <td><%= subscription.stripe_id %></td>
              <td class="text-right">
                <span><%= live_redirect "Show", to: Routes.admin_subscription_show_path(@socket, :show, subscription), class: "link link-primary" %></span>
              </td>
            </tr>
  <% end %>
          </tbody>
        </table>
      </div>
    </.admin_card>
  </div>
</div>